#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
    path: /gallery
    controller: App\Controller\ResponsiveGalleryController::gallery

app_bundle_route:
   path: /ajaxrequest
   controller: App\Controller\ResponsiveGalleryController::ajaxRequest